ec2_keypair: "MicHussey_KeyPair"
ec2_security_group: "sg-66aaa81d"
ec2_instance_type: "t2.micro"
#ec2_instance_type: "m4.large"
ec2_image: "ami-192a9460"  #CentOS-7 from 2017-12-05
#ec2_subnet_ids: ['subnet-1c48e16a']
ec2_region: "eu-west-1"
ec2_tag_Name: "Mic TestClient"
ec2_tag_Type: "MQTT Test Driver"
ec2_tag_Environment: "test"
ec2_volume_size: 30
test_keystore_password: solace1
solacecloud_mqtt_url: "{{ lookup('env','SOLACECLOUD_MQTT_URL') }}"
solacecloud_mqtt_uid: "{{ lookup('env','SOLACECLOUD_MQTT_UID') }}"
solacecloud_mqtt_password: "{{ lookup('env','SOLACECLOUD_MQTT_PASSWORD') }}"
awsiot_mqtt_url: "{{ lookup('env','AWS_MQTT_URL') }}"
