#!/usr/bin/env Rscript
# 
# Produce nice graphs of Latency data generated by SDKPerf
# 
# Author: michussey
###############################################################################
library("optparse")


option_list = list(
		make_option(c("-f", "--file"), type="character", default=NULL, 
				help="dataset file name", metavar="character"),
		make_option(c("-o", "--out"), type="character", default="output.png", 
				help="output file name [default= %default]", metavar="character")
); 

opt_parser = OptionParser(option_list=option_list);
opt = parse_args(opt_parser);

if (is.null(opt$file)){
	print_help(opt_parser)
	stop("At least one argument must be supplied (input file).n", call.=FALSE)
}

## Read the input data
a<-read.table(opt$file, header=FALSE, sep=",", col.names=paste0("C", 1:3))

total = sum(a$C3)
percentdist = cumsum(a$C3) / total * 100

## Set the output file name/type

png(file=opt$out, width=1600, height=800)
## Plot your data
# Set the margins of the graph
#par(mar = c(5,5,2,5))
# plot the data
barplot(a$C3,a$C2,ylab="Count",xlab=expression("Latency in " ~ mu * "s"))
axis(side = 1)

# Draw a second plot
par(new=T)
# Line chart is X,Y
plot(a$C2,percentdist,type="l", xlab=NA, ylab=NA, axes=F, pch=16)
axis(side = 4)
mtext(side = 4, line = 3, 'Cumulative Distribution (percent)')


## Close the graphics device (write to the output file)
dev.off()



