[local]
127.0.0.1 ansible_connection=local

[launched]
ec2-34-242-137-141.eu-west-1.compute.amazonaws.com ansible_python_interpreter=/usr/bin/python ec2_instanceid=i-004b42269242899a4 ec2_region=eu-west-1 ec2_public_ip=34.242.137.141 ansible_ssh_user=centos
