---
- name: Restart Client
  local_action:
    module: ec2
    state: 'restarted'
    wait: yes
    region: '{{ ec2_region }}'
    instance_ids: '{{ ec2_instanceid }}'

- name: Wait for the instances to start by checking the ssh port
  local_action:
    module: wait_for 
    host: "{{ec2_public_ip}}"
    port: 22
    delay: 60
    timeout: 320
    state: started
